version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./src:/var/www
      - ./docker-build/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - carpooling-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/var/www
      - ./docker-build/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - carpooling-network

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./docker-build/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - carpooling-network
  redis:
    image: redis:latest
    container_name: redis
   # command: ["redis-server", "--appendonly", "yes"]
   # hostname: redis
   # ports:
   #   - "6379:6379"
    networks:
      - carpooling-network
    #volumes:
    #  - redis-data:/data
#Docker Networks
networks:
  carpooling-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
